# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-26 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pictures',
            field=models.ImageField(null=True, upload_to='dating/photos'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pictures_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
