# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-27 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0003_auto_20190226_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pictures',
            field=models.ImageField(default='login/photo/default_male.gif', upload_to='photos'),
        ),
    ]
