# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-26 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=15)),
                ('seeking_for', models.CharField(max_length=15)),
                ('age_between', models.CharField(max_length=45)),
                ('zip_code', models.CharField(max_length=45)),
                ('summery', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_block', models.ManyToManyField(null=True, related_name='_user_user_block_+', to='login.User')),
                ('user_like', models.ManyToManyField(null=True, related_name='_user_user_like_+', to='login.User')),
            ],
        ),
    ]
