# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-27 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_block',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_like',
        ),
        migrations.AddField(
            model_name='userlike',
            name='like_by',
            field=models.ManyToManyField(related_name='like_by', to='login.User'),
        ),
        migrations.AddField(
            model_name='userlike',
            name='liked',
            field=models.ManyToManyField(related_name='liked', to='login.User'),
        ),
        migrations.AddField(
            model_name='userblock',
            name='block_by',
            field=models.ManyToManyField(related_name='block_by', to='login.User'),
        ),
        migrations.AddField(
            model_name='userblock',
            name='blocked',
            field=models.ManyToManyField(related_name='blocked', to='login.User'),
        ),
    ]
