# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190227_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userblock',
            name='block_by',
        ),
        migrations.AddField(
            model_name='userblock',
            name='block_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='block_by', to='login.User'),
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='blocked',
        ),
        migrations.AddField(
            model_name='userblock',
            name='blocked',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blocked', to='login.User'),
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='like_by',
        ),
        migrations.AddField(
            model_name='userlike',
            name='like_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='like_by', to='login.User'),
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='liked',
        ),
        migrations.AddField(
            model_name='userlike',
            name='liked',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='login.User'),
        ),
    ]
